### ISSUE TITLE
Support i.MX8

### ISSUE THREAD

**Issue by nvl1109** [WebPlatformForEmbedded/WPEBackend-rdk#42]
Hi,
Thank you for your great effort.
Do you have any plan/time for i.MX8 support? Thanks again.

**Comment by kraj** [comment]
latest should be supporting imx8 @moorthy-bs can you comment ?

**Comment by moorthy-bs** [comment]
Yes, latest wpeframework supports on i.MX8 with _wpeframework_ backend which is defaulted in [meta-wpe](https://github.com/WebPlatformForEmbedded/meta-wpe) master branch. As per the latest wpeframework, it enables _Westeros_ wayland compositor and wpe webkit will be a client to that.
i.MX8MQ enables Direct Rendering Manager (DRM) that westeros supports it. Westeros compositor with DRM backend, WPEBackend-rdk with _wpeframework_ backend and WPE Webkit 2.22 are validated on i.MX8MQ platform.

**Comment by nvl1109** [comment]
Thank you @kraj  and @moorthy-bs for the information.
Which yocto version/branch of freescale repos do you use in this case? Thank you.

**Comment by moorthy-bs** [comment]
Yes, latest supports on i.MX8. [meta-wpe](https://github.com/WebPlatformForEmbedded/meta-wpe) master branch enables _wpeframework_ backend which is defaulted (overcome _westeros_ backend). westeros-soc (gl implementation) for Direct Rendering Manager (DRM) to be enabled as i.MX8MQ supports DRM. WPEFramework's compositor plugin creates a Westeros wayland compositor under which webkit will be a client.
Overall, WPEFramework + webkit 2.22 with _wpeframework_ backend works fine on i.MX8MQ platform

**Comment by moorthy-bs** [comment]
latest [meta-freescale](https://github.com/Freescale/meta-freescale) master  branch support _warrior_ and _zeus_ yocto versions.

**Comment by nvl1109** [comment]
Thank you @moorthy-bs for helpful info.
Do you think the sumo branch of meta-wpe works with iMX8?
Actually, I use TechNexion iMX8M and there yocto layer is quite late (https://github.com/TechNexion/meta-edm-bsp-release). I will try to use meta-freescale with TechNexion kernel & u-boot. Hope it works.

**Comment by moorthy-bs** [comment]
meta-wpe master branch supports from sumo version.

**Comment by nvl1109** [comment]
@moorthy-bs I did try sumo branch of yocto + freescale + technexion, and meta-wpe master but I got some compile error. I will build again and post detail error in meta-wpe. Thank you.

**Comment by nvl1109** [comment]
I tried TechNexion sumo branch + meta-webkit master branch and got succeeded compile & run. Thank you all for your support.
